# Execution Time : List vs Numpy Array

In [4]:
import numpy as np

# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [5]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 196 ms, sys: 0 ns, total: 196 ms
Wall time: 197 ms


833332333333500000

In [6]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: user 3.16 ms, sys: 13 µs, total: 3.17 ms
Wall time: 3.06 ms


833332333333500000

# Create Numpy Array - 1d,2d,3d

In [14]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [15]:
arr_1d.shape


(4,)

In [16]:
arr_2d = np.array([(1,2,3,4),(3,4,5,6)])
arr_2d

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [17]:
arr_2d.shape

(2, 4)

In [18]:
arr_3d = np.array([(1,2,3),(4,5,6),(7,8,9)])
arr_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr_3d.shape

(3, 3)

In [31]:
# Make array with float values
arr_fl = np.array([(1,2,3),(4,5,6)],dtype=float)
arr_fl

array([[1., 2., 3.],
       [4., 5., 6.]])

# Special Numpy Arrays

In [23]:
# Array with zeros
arr_zero = np.zeros((3,5))
arr_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
# Array with ones | Make value --> int
arr_one = np.ones((4,2),dtype=int)
arr_one

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [28]:
# 3x2 matrix filled with 5
arr_desired = np.full((3,2),5)
arr_desired

array([[5, 5],
       [5, 5],
       [5, 5]])

In [35]:
# Make identity matrix
arr_iden = np.eye(4)
arr_iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
# Make Array With Random Values lies bw 0 to 1
arr_ran1 = np.random.random((3,4))
print(arr_ran1)

[[0.18072768 0.75854583 0.72774267 0.48284507]
 [0.22018632 0.41328085 0.28639383 0.60756325]
 [0.12851565 0.58815906 0.2687903  0.78675716]]


In [43]:
# Make Array With Random Desired Range ---> (min,max,(row,col))
arr_ran2 = np.random.randint(10,20,(3,4))
print(arr_ran2)

[[19 11 12 19]
 [10 18 19 19]
 [17 10 17 12]]


In [48]:
# For Only One Element lies in range
arr_ran2 = np.random.randint(10,20)
print(arr_ran2)

18


In [53]:
# Generate Array with Random Values --> row,col ko bracket me mat daalna
arr_ran3 = np.random.randn(3,5)
arr_ran3

array([[-0.75726438,  0.04985153,  0.05366542,  2.53276803, -0.13045198],
       [ 0.27629943, -0.67007684,  1.26643086,  1.31013942, -0.47762584],
       [-0.8182642 , -0.73075372, -1.02522367,  0.56910031,  1.30819962]])

In [58]:
# Create 1D array with evenly distributed in a given range : (min,max,no_of_values)
arr_lin = np.linspace(2,10,8)
arr_lin

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [59]:
# Create 1D array distributed by comm diff in a given range : (min,max,common_diff)
arr_arange = np.arange(2,10,3)
arr_arange

array([2, 5, 8])

# Analysing Numpy Array

In [60]:
# Making Random Array of 5x5
arr_rand = np.random.randint(1,10,(5,5))
print(arr_rand)

[[6 6 7 5 1]
 [6 9 5 2 9]
 [8 5 8 2 6]
 [8 7 2 4 9]
 [3 2 2 2 2]]


In [61]:
# Find Dimension
print(arr_rand.shape)

(5, 5)


In [62]:
# Number of Dimensions
print(arr_rand.ndim)

2


In [63]:
# No of elements in array
arr_rand.size

25

In [65]:
# Checking Data Type
arr_rand.dtype

dtype('int64')

# Mathematical Operations

In [66]:
# If we apply addition on list, it gets concatenated
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [70]:
# We can perform these operation on numpy arrays
a = np.array(list1)
b = np.array(list2)
print("Sum :",a+b)
print("Subtract :",a-b)
print("Multiply :",a*b)
print("Divide :",a/b)

Sum : [5 7 9]
Subtract : [-3 -3 -3]
Multiply : [ 4 10 18]
Divide : [0.25 0.4  0.5 ]


In [71]:
# Other Ways of doing the same
a = np.random.randint(1,5,(3,3))
b = np.random.randint(5,10,(3,3))
print(a)
print(b)

[[3 3 4]
 [4 3 3]
 [1 3 3]]
[[5 6 9]
 [5 7 9]
 [8 5 7]]


In [78]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 8  9 13]
 [ 9 10 12]
 [ 9  8 10]]
[[-2 -3 -5]
 [-1 -4 -6]
 [-7 -2 -4]]
[[15 18 36]
 [20 21 27]
 [ 8 15 21]]
[[0.6        0.5        0.44444444]
 [0.8        0.42857143 0.33333333]
 [0.125      0.6        0.42857143]]


# Array Manipulation

In [87]:
a = np.random.randint(0,10,(4,5))
print(a)

[[2 5 4 0 6]
 [2 7 9 0 2]
 [3 9 7 3 8]
 [3 7 2 0 5]]


In [88]:
# Transpose
print(np.transpose(a))
# print(a.T)

[[2 2 3 3]
 [5 7 9 7]
 [4 9 7 2]
 [0 0 3 0]
 [6 2 8 5]]


In [89]:
#Reshaping
print(a)
b = a.reshape(2,10)
print(b)

[[2 5 4 0 6]
 [2 7 9 0 2]
 [3 9 7 3 8]
 [3 7 2 0 5]]
[[2 5 4 0 6 2 7 9 0 2]
 [3 9 7 3 8 3 7 2 0 5]]


# Miscellaneous Part

In [91]:
rand_arr = np.random.randint(1,20,(4,5))
print(rand_arr)

[[ 5  6 19  9  5]
 [ 3  9 18  3 16]
 [14 12 15 12  8]
 [ 5  5  7 13 10]]


In [92]:
# Accessing all the elem greater than 5
rand_arr[rand_arr>5]

array([ 6, 19,  9,  9, 18, 16, 14, 12, 15, 12,  8,  7, 13, 10])

In [93]:
# Multiplying with number
print(rand_arr)
print(rand_arr*2)

[[ 5  6 19  9  5]
 [ 3  9 18  3 16]
 [14 12 15 12  8]
 [ 5  5  7 13 10]]
[[10 12 38 18 10]
 [ 6 18 36  6 32]
 [28 24 30 24 16]
 [10 10 14 26 20]]


In [97]:
# Accessing min, max
print(np.amin(rand_arr))
print(np.amax(rand_arr))

3
19


In [98]:
# Avg of array
print(np.mean(rand_arr))

9.7
